runtime: custom
env: flex
service: backend

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 10

skip_files:
- node_modules/
- test*.js
- ^(.*/)?.*\.md$