# FROM ubuntu:latest
FROM node:8

MAINTAINER Eric Bidelman <ebidel@>

# # Install missing shared libs for Chromium.
# RUN apt-get update && \
# apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
# libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
# libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
# libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
# ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

# Install latest chrome (dev) package.
# Note: this also installs the necessary libs so we don't need the previous RUN command.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
apt-get update &&\
apt-get install -y google-chrome-unstable

# Install deps for server.
COPY package.json /
RUN yarn

# Install puppeteer so it can be required by user code that gets ran in server.js.
RUN yarn add puppeteer
# RUN rm -rf /node_modules/puppeteer/.local-chromium

COPY src /src/

EXPOSE 8080

# ENTRYPOINT ["/src/entrypoint.sh"]
# CMD ["google-chrome-unstable", "--no-sandbox"]
CMD ["yarn", "start"]
